# Generated by Django 2.0.7 on 2018-08-15 15:28
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.models import User

def InitialData(apps, schema_editor):
    user = User.objects.create_user(username='superadmin', email='admin@paradigma.com.ar', password='adm007bb')
    user.is_superuser = True
    user.is_staff = True
    user.first_name = "ADMINISTRADOR"
    user.last_name = "PARADIGMA"
    user.save()

    Grupos = apps.get_model('users', 'Grupos')
    grupo = Grupos()
    grupo.nombre = "SISTEMA"
    grupo.save()

    PerfilModel = apps.get_model('users', 'Perfil')
    perfil = PerfilModel()
    perfil.user_id = user.id
    perfil.save()

    perfil.grupos.add(grupo)
    perfil.save()

    Permisos(apps, schema_editor)


def Permisos(apps, schema_editor):
    view = {'nombre': 'view', 'descripcion': 'Ver Lista'}
    create = {'nombre': 'new', 'descripcion': 'Agregar'}
    edit = {'nombre': 'edit', 'descripcion': 'Editar'}
    detail = {'nombre': 'detail', 'descripcion': 'Ver'}
    delete = {'nombre': 'delete', 'descripcion': 'Eliminar'}

    permisos = [{
        'nombre': 'usuarios',
        'descripcion': 'Usuarios',
        'hijos':[{
            'nombre': 'usuarios',
            'descripcion': 'Usuarios',
            'hijos':[view, create, edit, detail, delete, 
                {'nombre': 'lock', 'descripcion': 'Deshabilitar', },
                {'nombre': 'unlock', 'descripcion': 'Habilitar', },
            ],
        },
        {
            'nombre': 'grupos',
            'descripcion': 'Grupos',
            'hijos': [view, create, edit, detail, delete,]
        }]
    },]

    MigratePermisos(permisos, apps, schema_editor)


def MigratePermisos(permisos, apps, schema_editor, previous_name = ""):
    Permiso = apps.get_model('users', 'Permisos')

    objs = []
    for permiso in permisos:
        if 'hijos' in permiso.keys():
            hijos = MigratePermisos(permiso['hijos'], apps, schema_editor, permiso['nombre'])
            permiso.pop('hijos', None)
            obj = Permiso(**permiso)
            
            if previous_name != "":
                obj.nombre = previous_name + "_" + obj.nombre
            
            obj.save()
            obj.permisos_set.set(hijos)
            objs.append(obj)
        else:
            obj = Permiso(**permiso)
            
            if previous_name != "":
                obj.nombre = previous_name + "_" + obj.nombre
            
            obj.save()
            objs.append(obj)
    return objs
            

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupos', models.ManyToManyField(to='users.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Permisos')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='permisos',
            field=models.ManyToManyField(to='users.Permisos'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupos',
            name='permisos',
            field=models.ManyToManyField(to='users.Permisos'),
        ),
        migrations.RunPython(InitialData),
    ]
