# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil_accesosdirectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='accesosDirectos',
            field=models.TextField(default='[]'),
        ),
    ]
