# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultconfig',
            name='decimalesChar',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.AlterField(
            model_name='defaultconfig',
            name='milesChar',
            field=models.CharField(default=',', max_length=1),
        ),
    ]
